---
- name: install initial packages on all boxes
  hosts: all
  remote_user: ansible
  become: yes
  
  tasks:
  - name: install all initial packages
    yum:
      name: ['man', 'man-pages', 'mlocate', 'vim', 'bind','bind-utils','ftp','epel-release']
      state: latest