---
- name: Installing  apache webserver
  hosts: web8
  become: yes
  tasks:
    - name: Installing a package
      yum:
        name: httpd
        state: present

    - name: Start and enable a service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Add firewall rule
      firewalld:
        state: enabled
        service: http
        permanent: yes
        immediate: yes

    - name: Add index.html file
      copy:
        dest: /var/www/html/index.html
        content: "This is a list webserver we created with ansible"

