---
# tasks file for database.mysql
- name: Install epel-release 
  yum:
    name: "epel-release"
    state: latest 

- name: Install packages 
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ list_packages }}" 

- name: Start and enable httpd
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_list }}"

- name: Mysql Secure Installation
  community.mysql.mysql_user:
    name: root
    password: "{{ roots_password }}"
    login_password: "{{ roots_password }}"

- name: Copy phpadmin template
  template:
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
    src: phpMyAdmin.conf.j2

- name: Add services to the firewall
  firewalld:
    state: enabled
    service: "{{ item }}"
    permanent: yes
    immediate: yes
  loop: "{{ firewall_service }}"

- name:  Restart httpd
  service:
    name: httpd
    state: restarted     